######################## default configuration ####################
baseURL = "https://appcodify.com/"
title = "Codderlly: Learn iOS, Xcode, Swift, SwiftUI and Flutter."
description = "A Developement Blog about iOS, Xcode, Swift, SwiftUI and Flutter. Learn how to build better apps."
theme = "geeky-hugo"
languageName = "En"
languageCode = "en-us"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

# post pagination
paginate = "4"
listPaginate = "9"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "G-LYMK2NK7Y7"
# disqus short name
# disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"


[sitemap]
changefreq = "always"
priority = 0.5
filename = "sitemap.xml"
############################ Twitter Card ###########################
[params]
Twitter_Image = "images/twitter_card.png"
Twitter_Site = "@RaulFerrer_dev"
Image = "images/twitter_card.png"
author = "Raúl Ferrer"
github = "https://github.com/raulferrerdev"
og_image = "images/twittercard.png"
itename = "Codderlly"
twitter = "@RaulFerrer_dev"