############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Swift"
url = "tags/swift/"
weight = 2

[[main]]
name = "Flutter"
url = "tags/flutter/"
weight = 3

[[main]]
name = "About"
url = "about/"
weight = 4

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Swift"
url = "tags/swift/"
weight = 2

[[footer]]
name = "Flutter"
url = "tags/flutter/"
weight = 3

[[footer]]
name = "About"
url = "about/"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 5
