#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logoColor = "images/Logo-red.png"

# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "200x"
logoColor_width = "200x"

# logo text will only show when logo is missing.
logo_text = "Codderlly"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "All about Mobile Developement: Swift, Xcode, iOS, Flutter... *If you like the world of software development, maybe here you will find what you are looking for."
author = "Raúl Ferrer"
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own
# contact info
# address = ""
mobile = ""
email = "developer.blog@icloud.com"
# contact form action
# contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Sections"
recent_post_title = "Recent Posts"
mainSections = ["blog"]
# about widget content
about_widget_content = "Mobile Tech Lead & Senior iOS Developer. Devising, developing and managing new projects. Always learning!"
# footer content
# footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
# copyright
copyright = "@2022 Raúl Ferrer"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to Codderlly"
image = ""
background_image = ""
content = "**If you like the world of software development, maybe here you will find what you are looking for.**"
button_label = "Know About Me"
button_link = "about/"

# Advertise
# [advertisement]
# image = "images/promotion.png"
# link = "https://gethugothemes.com/"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


# [[social]]
# title = "facebook"
# icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/RaulFerrer_dev"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/raulferrerdev/"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/raulferrerdev"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://es.linkedin.com/in/raulferrergarcia"